name: PatunganYuk CRM Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cp .env.example .env
          composer install
          php artisan key:generate --ansi

      - name: Deploy Laravel Project
        if: github.ref == 'refs/heads/main'
        run: |
          sshpass -p 'LibrA21101998' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ patunganyuk@153.92.5.213:/home/patunganyuk/repo/patungan-lp/
          sshpass -p 'LibrA21101998' ssh -o StrictHostKeyChecking=no patunganyuk@153.92.5.213 'cd /home/patunganyuk/repo/patungan-lp && php artisan config:cache && php artisan route:cache && php artisan view:cache'
          sshpass -p 'LibrA21101998' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" /home/patunganyuk/repo/patungan-lp/public/ patunganyuk@153.92.5.213:/home/patunganyuk/public_html/

      - name: Set Permissions
        run: |
          sshpass -p 'LibrA21101998' ssh -o StrictHostKeyChecking=no patunganyuk@153.92.5.213 'find /home/patunganyuk/repo/patungan-lp/storage/ -type d -exec chmod 775 {} \;'
          sshpass -p 'LibrA21101998' ssh -o StrictHostKeyChecking=no patunganyuk@153.92.5.213 'find /home/patunganyuk/repo/patungan-lp/bootstrap/cache/ -type d -exec chmod 775 {} \;'
